Dom
ChernelEvgeni/Fpm pull request #7
Opened 2018-03-12 20:13 UTC by ChernelEvgeni

2018-03-18 10:17 UTC, ala-n requested changes
Все доработать!
Тут копипаст чужих ошибок, местами жутчайшая дич.
Задания до 3/4 выполнены плохо, от 5 тут только ошметки.

2018-03-18 10:17 UTC, ala-n commented on Site/index.html
> +<html lang="rus">
lang="ru"
сокращение ru а не rus

2018-03-18 10:17 UTC, ala-n commented on Site/index.html
> +        <a href="HomePage.html">Pinnsvin</a>
alt аттрибут для всех картинок !!!!

2018-03-18 10:17 UTC, ala-n commented on Site/index.html
> +    <div class="container1">
Классы под 1 стиль именования это - 1
О чем говорит единица в конце названия этого класса - загадка - это 2.

2018-03-18 10:17 UTC, ala-n commented on Site/index.html
> +                <input type="text" placeholder="Введите имя" />
Если используешь форму то это должно быть оправдано. Форма это функциональный элемент в первую очередь!!! это не просто тег для групировки, форма существовала до 5 стандарта HTML, она существует не для семантики. Почитать об этом обязательно!!!
У инпутов в форме должны быть атрибуты name, иначе все бесполезно!!!!!
И тогда тебе не нужны никакие id шники элементов этой формы в JS, а вот для формы id-шник пригодится.
ты сделаешь 
```
let form = document.getElementById('formId');
let data = new FormData(form);
// data.get(name) - returns the value 
```

2018-03-18 10:17 UTC, ala-n commented on Site/index.html
> +            <button id="SizeButtoonSeach"><p >Поиск</p></button>
эту кнопку тоже если юзаешь форму помечать надо не id а type="submit"

2018-03-18 10:17 UTC, ala-n commented on Site/index.html
> +            <form class="Input">
Для 6 задания:
1. когда форма сабмитается, происходит событие submit
2. по умолчанию форма пытается отправить свое состояние на сервер и открыть ответ на новой странице/вкладке.

Поэтому порядок таков, не слушем клик кнопки "Поиск", а слушаем форму:
```
form.addEventListener('submit', (e) => {
e.preventDefault(); // чтобы ничего никуда не пошло по дефолтному поведению
...
});
```

2018-03-18 10:17 UTC, ala-n commented on Site/index.html
> +            <br/>
от br избавится, сделать все через margin/padding

2018-03-18 10:17 UTC, ala-n commented on Site/index.html
> +            <button class="ButttonAddPhoto"><p>Добавить фото</p></button>
p - блочный элемент, какого, извиняюсь, он внутри кнопки делает

2018-03-18 10:17 UTC, ala-n commented on Site/index.html
> +<main class="Color">
порясающее название класса, прям оччень понятно что за он

2018-03-18 10:17 UTC, ala-n commented on Site/index.html
> +<section class="Info">
Хоть id шник бы был...

2018-03-18 10:17 UTC, ala-n commented on Site/js/main.js
> +var postsFunction =(function() {
Дежавю, однако, гдето я похожее название уже читал, и от перемены слов оно лучше тоже не стало...

2018-03-18 10:17 UTC, ala-n commented on Site/js/main.js
> +        if (typeof  photoPost.id === 'string' && typeof photoPost.descriprion === 'string' && photoPost.createdAt instanceof Date &&
а можно просто вернуть результат того что внутри условия if

2018-03-18 10:17 UTC, ala-n commented on Site/js/main.js
> +    function editPhotoPost(id, photopost){
WAT?? что за дичь тут происходит ??

2018-03-18 10:17 UTC, ala-n commented on Site/js/main.js
> +           return(a.createdAt) - (b.createdAt);
скобки итить их нахрена копипастим, смысла в них нету ни здесь ни в оригинале.

2018-03-18 10:17 UTC, ala-n commented on Site/js/main.js
> +    function removePhotoPost(string){
string - ??? 
PS: блоки ставим всегда, даже когда 1 оператор.

2018-03-18 10:17 UTC, ala-n commented on Site/js/main.js
> + var array = new Array();
let array = [];
Не читаем материалы лекций!!!!!!!!

2018-03-18 10:17 UTC, ala-n commented on Site/script.js
> +
И все?
пост создали но никуда не добавили?
не работет оно...

2018-03-18 10:17 UTC, ala-n commented on task4/main.js
> +(function() {
WAT а это что за файл...
Итить ***.
Убрать все лишнее!!!!!
оставить только то что нужно.

2018-03-18 10:17 UTC, ala-n commented on task4/main.js
> +    function CountCorrectlyFild(Object) {
Ох ...
Никогда не называть переменные с большой буквы и тем более именами встроенных обьектов !!!!!!!!!!

2018-03-18 10:17 UTC, ala-n commented on task4/main.js
> +    function CountCorrectlyFild(Object) {
Так дальше дич еще похлеще того что было ранее...

2018-03-19 17:42 UTC, djadjka commented on Site/script.js
> +            buttonEdit.innerHTML = "<img src=\"img/edit.jpg\"  alt=\"edit\" class=\"edit\">";
в js мы используем одинарные, а в html двойные ковычки, чтобы вот такой фигни не было

2018-03-19 17:43 UTC, djadjka commented on Site/script.js
> +        datePhoto.innerHTML = getFormatDate(photoPost)+" (" +getFormatTime(photoPost)+")";
тут можно использовать шаблоны, и луче заюзать textContent

2018-03-19 17:49 UTC, djadjka commented on Site/script.js
> +        for (var i = 0; i < photoPost.length; i++)
скобки

2018-03-19 17:51 UTC, djadjka commented on Site/script.js
> +        countPrintPost++;
вот вообще хз зачем эта переменная, почему просто не вохвращать length ? 
потом все будет очень грустно когда им будут пользоваться несколько человек

2018-03-19 17:53 UTC, djadjka commented on Site/script.js
> +        countPrintPost++;
эммм, а почему тут (и далее) ничего не происходит с отображением ? добавили и перезагружаем стр ?

2018-03-19 17:54 UTC, djadjka commented on Site/script.js
> +        if (day < 10) day = "0" + day;
это очень сложно читать

2018-03-19 17:55 UTC, djadjka commented on Site/script.js
> +    function getFormatDate(post) {
эмм, а почему бы не передавать сюда дату, а не пост ? 
если тебе еще где-то понадобится форматировать дату ты будешь новую функцию писать ?

2018-03-19 18:04 UTC, djadjka commented on Site/script.js
> +console.log(moduleDom.addPost( {
c тестами и данными  вообще какая-то дичь

2018-03-20 14:52 UTC, djadjka commented
![image](https://user-images.githubusercontent.com/12067451/37662142-75c05538-2c67-11e8-9fb2-1cfe0702ae4c.png)

2018-03-20 14:54 UTC, djadjka commented
setButtonDownload()
почему ты ее не вызываешь ? 
почему блин тесты опять закоменчины ?

2018-03-20 14:59 UTC, djadjka commented on Site/script.js
> +    function updatePost() {
а это что ?

2018-03-20 15:03 UTC, djadjka commented on Site/script.js
> +moduleDom.showPosts(0,moduleDom.getSizePost());
30 раз перепроверь блин, что ты отправляешь...
не надо коментить тесты

2018-05-08 10:40 UTC, merged

2018-05-14 12:56 UTC, djadjka commented on Site/script.js
> +            buttonEdit.innerHTML = "<img src=\"img/edit.jpg\"  alt=\"edit\" class=\"edit\">";
сейчас "<img src='img/edit.jpg'  alt='edit' class='edit'>"
должно '<img src="img/edit.jpg"  alt="edit" class="edit">"